### ISSUE TITLE
Consider getting rid of platform_utils or moving it inside the repo

### ISSUE THREAD

**Issue by Menelion** [manuelcortez/music-dl#3]
As the platform_utils library is at Christopher toth's Mercurial that has been showing HTTP 502 Bad Gateway for two days already, I'd suggest either get rid of it completely (if the app is actually not cross-platform) or move it inside the repository itself.

**Comment by Menelion** [comment]
After looking at the code more thoroughly, I see that you use only the `paths` module. I could bring this single file into the repo and correct the appropriate imports. If it's good for you, I'll send a PR in a day or two.

**Comment by manuelcortez** [comment]
Hi, it would be neat, thank you.
